services:
  - type: web
    name: rss-trigger
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: REPO_SLUG
        value: pshutov/rss-gamefound-spotlight
      - key: CODE_BRANCH
        value: main
      - key: GIT_USER_NAME
        value: "Render Bot"
      - key: GIT_USER_EMAIL
        value: "noreplay@renderbot.com"
      - key: RSS_OUTPUT_PATH
        value: "gamefound_spotlight.xml"
      - key: USE_DB
        value: "false"
      # set these in Render dashboard as secrets (not committed):
      # - GH_PAT
      # - GF_API (optional)
      # - CRON_TOKEN
